[package]
name = "rsh"
version = "0.1.0"
authors = ["Tyler Philbrick <tyler@tylerphilbrick.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
logos = "0.11"
